### ISSUE TITLE
建议增加nginx相关配置及环境搭建方案

### ISSUE THREAD

**Issue by xwjchina** [phpstudyOne/rihui#17]

**Comment by phpstudyOne** [comment]
server {
    charset utf-8;
    client_max_body_size 128M;
 
    listen 80; ## listen for ipv4
    #listen [::]:80 default_server ipv6only=on; ## listen for ipv6
    server_name www.lite.com;
    root        /var/www/html/rihui/lite;
    index       index.php;

    access_log  /var/www/html/rihui/log/access.log;
    error_log   /var/www/html/rihui/log/error.log;

    location / {
        # Redirect everything that isn't a real file to index.php
        try_files $uri $uri/ /index.php$is_args$args;
    }

     # uncomment to avoid processing of calls to non-existing static files by     Yii
     #location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
     #    try_files $uri =404;
     #}
     #error_page 404 /404.html;
 
    location ~ \.php$ {
            include snippets/fastcgi-php.conf;
    #
    #       # With php7.0-cgi alone:
    #       fastcgi_pass 127.0.0.1:9000;
    #       # With php7.0-fpm:
            fastcgi_pass unix:/run/php/php7.0-fpm.sock;
     }

 
     location ~ /\.(ht|svn|git) {
         deny all;
     }
 }

```conf

**以上配置针对php7**

如果是php<= 5.6 `  location ~ \.php$` 配置使用 `fastcgi_pass 127.0.0.1:9000;`

**Comment by phpstudyOne** [comment]
Issue moved to [phpstudyOne/lite #12](https://github.com/phpstudyOne/lite/issues/12) via [**ZenHub**](https://www.zenhub.com/)
